version: '3.8'

networks:
  data_pipeline_network:
    external: true

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: unless-stopped
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - data_pipeline_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 30s
      timeout: 10s
      retries: 3

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: unless-stopped
    depends_on:
      - namenode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SERVICE_PRECONDITION=namenode:9000
    ports:
      - "9864:9864"
    networks:
      - data_pipeline_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9864"]
      interval: 30s
      timeout: 10s
      retries: 3

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    restart: unless-stopped
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./config/hive.env
    environment:
      - "HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore"
      - "SERVICE_PRECONDITION=hive-metastore:9083"
    ports:
      - "10000:10000"
      - "10002:10002"
    networks:
      - data_pipeline_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "10000"]
      interval: 30s
      timeout: 10s
      retries: 3

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    restart: unless-stopped
    depends_on:
      - namenode
      - datanode
      - hive-metastore-postgresql
    env_file:
      - ./config/hive.env
    environment:
      - "HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore-postgresql/metastore"
      - SERVICE_PRECONDITION=namenode:9000 datanode:9864 hive-metastore-postgresql:5432
    command: /opt/hive/bin/hive --service metastore
    ports:
      - "9083:9083"
    networks:
      - data_pipeline_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9083"]
      interval: 30s
      timeout: 10s
      retries: 3

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    restart: unless-stopped
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - data_pipeline_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "hive"]
      interval: 10s
      timeout: 5s
      retries: 3
